server:
  #访问端口号
  port: 8080
  servlet:
    #请求路径
    context-path: /dcims
  tomcat:
    uri-encoding: utf-8
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 15611930107abcD*
    url: jdbc:mysql://mayanze.com:3306/mayanze-dcims?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    hikari:
      max-lifetime: 600000
  #返回date给前端的格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#请求日志忽略项
requestLog:
    ignores: request-log
